---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
        name: kubeslice-demo
    spec:
      serviceAccountName: default
      containers:
      - name: server-shippingservice
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.4.1
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051

---
apiVersion: networking.kubeslice.io/v1beta1
kind: ServiceExport
metadata:
  name: shipping-service
spec:
  slice: boutique-slice
  selector:
    matchLabels:
      app: shippingservice
      name: kubeslice-demo
  ports:
  - name: tcp
    containerPort: 50051
    protocol: TCP