---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
        name: kubeslice-demo
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server-currencyservice
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.4.1
        ports:
        - name: grpc
          containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000

---
apiVersion: networking.kubeslice.io/v1beta1
kind: ServiceExport
metadata:
  name: currency-service
spec:
  slice: boutique-slice
  selector:
    matchLabels:
      app: currencyservice
      name: kubeslice-demo
  ports:
  - name: tcp
    containerPort: 7000
    protocol: TCP