apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.3.8
          ports:
          - containerPort: 5050
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.boutique.svc.slice.local:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.boutique.svc.slice.local:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice.boutique.svc.slice.local:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice.boutique.svc.slice.local:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.boutique.svc.slice.local:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.boutique.svc.slice.local:7070"
          - name: DISABLE_STATS
            value: "1"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: checkoutservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkoutservice
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
---
apiVersion: networking.kubeslice.io/v1beta1
kind: ServiceExport
metadata:
  name: checkoutservice
spec:
  slice: water
  selector:
    matchLabels:
      app: checkoutservice
  ingressEnabled: false
  ports:
  - name: tcp
    containerPort: 5050
    protocol: TCP
