apiVersion: controller.kubeslice.io/v1alpha1
kind: SliceConfig
metadata:
  name: demo-slice
  namespace: kubeslice-mongodb-project
spec:
  sliceSubnet: 192.168.0.0/16
  sliceType: Application
  sliceGatewayProvider:
    sliceGatewayType: OpenVPN
    sliceCaType: Local
    sliceGatewayServiceType:
      - cluster: worker-1
        type: LoadBalancer
        protocol: TCP
      - cluster: worker-2
        type: LoadBalancer
        protocol: TCP
      - cluster: worker-3
        type: LoadBalancer
        protocol: TCP
  sliceIpamType: Local
  clusters:
    - worker-1
    - worker-2
    - worker-3
  qosProfileDetails:
    queueType: HTB
    priority: 1
    tcType: BANDWIDTH_CONTROL
    bandwidthCeilingKbps: 5120
    bandwidthGuaranteedKbps: 2560
    dscpClass: AF11
  namespaceIsolationProfile:
    applicationNamespaces:
    - namespace: mongodb
      clusters:
      - worker-1
      - worker-2
      - worker-3
    - namespace: mongo-sh
      clusters:
      - worker-1
    isolationEnabled: false                   #make this true in case you want to enable isolation
    allowedNamespaces:
     - namespace: kube-system
       clusters:
       - worker-1
       - worker-2
       - worker-3
